### ISSUE TITLE
Needs to update API doc for generic parser-combinators such as `many(p)`

### ISSUE THREAD

**Issue by mori0091** [mori0091/cparsec2#33]
**Describe the bug**
Relative to #28
Description of some parser-combinators should be updated.
- [ ] `many(p)` (refactored at #31)
- [ ] `many1(p)` (refactored at #31)
- [ ] `seq(p, ...)` (refactored at #32)
- [ ] `cons(p, ps)` (refactored at #34)

**To Reproduce**
See API docs.

**Expected behavior**
The above four parser-combinators are now a generic parser-combinator.
Supporting type of its arguments and return value (parser) should be described.

**Development environment (please complete the following information):**
 - OS and version: [e.g. Ubuntu 18.04]
 - Compiler and version: [e.g. gcc 7.4.0, g++ 7.4.0]

**Additional context**
